// 按需全局引入 vant组件
import Vue from 'vue'
import {
  Grid,
  GridItem,
  Button,
  List,
  Cell,
  CellGroup,
  Tabbar,
  TabbarItem,
  Form,
  Field,
  Switch,
  Toast,
  Dialog,
  NavBar,
  Sidebar,
  SidebarItem,
  Col,
  Row,
  Card,
  Tag,
  Sticky,
  Stepper,
  GoodsAction,
  GoodsActionIcon,
  GoodsActionButton,
  Popup,
  Empty,
  Icon,
  Panel,
  PullRefresh,
  Search,
  NoticeBar,
  Calendar,
  Picker,
  DatetimePicker,
  ActionSheet,
  Image as VanImage,
  Tab,
  Tabs,
  Radio,
  RadioGroup,
  Collapse,
  CollapseItem,
  SwipeCell,
  Checkbox,
  SubmitBar,
  Divider
} from 'vant'
Vue.use(Button)
Vue.use(Cell)
Vue.use(CellGroup)
Vue.use(Grid).use(GridItem)
Vue.use(List)
Vue.use(Tabbar).use(TabbarItem)
Vue.use(Form)
Vue.use(Field)
Vue.use(Switch)
Vue.use(Toast)
Vue.use(Dialog)
Vue.use(NavBar)
Vue.use(Sidebar).use(SidebarItem)
Vue.use(Col)
Vue.use(Row)
Vue.use(Card)
Vue.use(Tag)
Vue.use(Sticky)
Vue.use(Stepper)
Vue.use(GoodsAction)
Vue.use(GoodsActionButton)
Vue.use(GoodsActionIcon)
Vue.use(Popup)
Vue.use(Empty)
Vue.use(Icon)
Vue.use(Panel)
Vue.use(PullRefresh)
Vue.use(Search)
Vue.use(NoticeBar)
Vue.use(Calendar)
Vue.use(Picker)
Vue.use(DatetimePicker)
Vue.use(ActionSheet)
Vue.use(VanImage)
Vue.use(Tabs).use(Tab)
Vue.use(RadioGroup).use(Radio)
Vue.use(Collapse).use(CollapseItem)
Vue.use(SwipeCell)
Vue.use(Checkbox)
Vue.use(SubmitBar)
Vue.use(Divider)
